baseURL = "https://osteopathe-valdoingt.fr"
languageCode = "fr-fr"
title = "Mathilde LARATTE Osteopathe"
googleAnalytics = "G-19W4T6JZFK"

theme = ["mathildelaratte"]

enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params.meta]
  title = "Mathilde LARATTE - Ostéopathe - Bois d'Oingt, Val d'Oingt"
  description = "Mathilde LARATTE - Ostéopathe - Le Bourg Place du Chateau - 63 Place de la Libération 69620 Bois d'Oingt, Val d'Oingt"
  keywords = ["ostéopathe", "Val d'Oingt", "Bois d'Oingt", "Bagnols", "Ostéopathe", "osteo bois d'oingt"]
