baseURL = "https://osteopathe-bagnols.netlify.app"
languageCode = "fr-fr"
title = "Mathilde LARATTE Osteopathe"
googleAnalytics = "UA-131748760-1"

theme = ["mathildelaratte"]

enableRobotsTXT = true
canonifyURLs = true

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[params.meta]
  title = "Mathilde LARATTE - Ostéopathe - Bagnols"
  description = "Mathilde LARATTE - Ostéopathe - Le Bourg Place du Chateau - Bagnols"
  keywords = ["ostéopathe", "Val d'Oingt", "Bois d'Oingt", "Bagnols", "Ostéopathe", "osteo bois d'oingt"]
