# theme.toml template for a Hugo theme

name = "ML"
license = "MIT"
licenselink = "https://github.com/mmatur/mathildelaratte.website/blob/master/LICENSE"
# homepage = "https://osteopathe-bagnols.fr/"
homepage = "https://osteopathe-bagnols.netlify.app/"
description = "Mathilde LARATTE - Ostéopathe - Le Bourg Place du Chateau - Bagnols"
tags = ["ostéopathe", "Val d'Oingt", "Bagnols", "Le Bois d'Oingt", "Ostéopathe", "osteo bois d'oingt", "osteo bagnols"]
features = []
min_version = "0.41"

[author]
  name = "mmatur"
  homepage = "https://github.com/mmatur"
